### ISSUE TITLE
database connection leak observed in TFB

### ISSUE THREAD

**Issue by michaelhixson** [TechEmpower/gemini#85]
Gemini appears to continuously close and reopen connections to the database in the TFB updates test.  In the Citrine environment, it does this quickly enough and for long enough that the operating system runs out of connections.

Reproduction steps from the root directory of TFB:

1. [terminal#1] `tfb --test gemini-mysql --mode debug`
2. [terminal#2] `docker ps | grep gemini-mysql` to find the container id
3. [terminal#2] `docker exec -it bash <container-id>`
4. [terminal#2] Inside the gemini-mysql container, run `watch 'ss -tan | wc -l'` to continuously print out the total number of connections.  **Edit:** If `watch` and `ss` aren't installed, do `apt get update && apt-get install -y procps iproute2`
5. [terminal#3]  `docker run --rm techempower/tfb.wrk wrk -H 'Host: host.docker.internal' -H 'Accept: application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' --latency -d 15 -c 512 --timeout 8 -t 8 "http://host.docker.internal:8080/update?queries=20"`
6. [terminal#2] watch the number of connections climb continuously

The application logs ([example from a recent run](https://tfb-status.techempower.com/unzip/results.2020-04-20-07-27-56-665.zip/results/20200415180849/gemini-mysql/run/gemini-mysql.log)) include a whole lot of messages like this:
```
gemini-mysql: GH 02:48:05 jdCA: none - 1322 - [c269;t-1] Closing connection profile 269.
gemini-mysql: GH 02:48:05 jdCA: none - 1325 - [c273;t-1] Closing connection profile 273.
gemini-mysql: GH 02:48:05 jdCA: none - 1311 - [c262;t-1] Closing connection profile 262.
gemini-mysql: GH 02:48:05 jdCA: none - 1335 - [c284;t-1] Closing connection profile 284.
```

Why is it closing connections?  I was able to find the part of gemini's code that writes that message, but it wasn't clear what was calling that function or why.

In the Citrine benchmarking environment, once it runs through 50,000 or so connections like that, the operating system runs out of connections to give gemini.  That's when the "Cannot assign requested address" errors start.

```
gemini-mysql: GH 02:50:53 jdCA: none - 15467940 - [c50317;t-1] Closing connection profile 50317.
gemini-mysql: GH 02:50:53 jdCA: none - 15480057 - [c50396;t-1] Closing connection profile 50396.
gemini-mysql: GH 02:50:53 jdCA: none - 15468372 - [c50336;t-1] Closing connection profile 50336.
gemini-mysql: GH 02:50:54 jdCA: none - 15483057 - none - 15483057 - [c50512;t-1] SQL Exception while connecting. com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
gemini-mysql: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
gemini-mysql: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
gemini-mysql: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
gemini-mysql: 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
gemini-mysql: 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
gemini-mysql: 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:199)
gemini-mysql: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
gemini-mysql: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
gemini-mysql: 	at com.techempower.data.jdbc.JdbcConnectionProfile.establishDatabaseConnection(JdbcConnectionProfile.java:182)
gemini-mysql: 	at com.techempower.data.jdbc.JdbcConnectionManager.createConnectedProfile(JdbcConnectionManager.java:597)
gemini-mysql: 	at com.techempower.data.jdbc.JdbcConnectionManager.addNewProfile(JdbcConnectionManager.java:195)
gemini-mysql: 	at com.techempower.data.jdbc.JdbcConnectionManager.getAnyAvailableProfile(JdbcConnectionManager.java:464)
gemini-mysql: 	at com.techempower.data.jdbc.JdbcConnectionManager.getProfile(JdbcConnectionManager.java:404)
gemini-mysql: 	at com.techempower.data.jdbc.JdbcConnectionManager.getConnectionMonitor(JdbcConnectionManager.java:495)
gemini-mysql: 	at com.techempower.data.jdbc.BasicConnectorFactory.getConnectionMonitor(BasicConnectorFactory.java:354)
gemini-mysql: 	at com.techempower.data.EntityGroup.get(EntityGroup.java:396)
gemini-mysql: 	at com.techempower.cache.EntityStore.get(EntityStore.java:775)
gemini-mysql: 	at hello.home.handler.HelloHandler.multipleQueries(HelloHandler.java:74)
gemini-mysql: 	at hello.home.handler.HelloHandlerMethodAccess.invoke(Unknown Source)
gemini-mysql: 	at com.techempower.gemini.path.MethodSegmentHandler.dispatchToAnnotatedMethod(MethodSegmentHandler.java:495)
gemini-mysql: 	at com.techempower.gemini.path.MethodSegmentHandler.handle(MethodSegmentHandler.java:388)
gemini-mysql: 	at com.techempower.gemini.path.PathDispatcher.dispatch(PathDispatcher.java:249)
gemini-mysql: 	at com.techempower.gemini.GeminiApplication.handleRequest(GeminiApplication.java:1077)
gemini-mysql: 	at com.techempower.gemini.GeminiApplication.doRequest(GeminiApplication.java:1021)
gemini-mysql: 	at com.techempower.gemini.transport.InfrastructureServlet.service(InfrastructureServlet.java:168)
gemini-mysql: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:97)
gemini-mysql: 	at com.caucho.server.dispatch.ServletFilterChain.doFilter(ServletFilterChain.java:109)
gemini-mysql: 	at com.caucho.server.webapp.WebAppFilterChain.doFilter(WebAppFilterChain.java:156)
gemini-mysql: 	at com.caucho.server.dispatch.ServletInvocation.service(ServletInvocation.java:314)
gemini-mysql: 	at com.caucho.server.http.HttpRequest.handleRequest(HttpRequest.java:843)
gemini-mysql: 	at com.caucho.network.listen.TcpSocketLink.dispatchRequest(TcpSocketLink.java:1393)
gemini-mysql: 	at com.caucho.network.listen.TcpSocketLink.handleRequest(TcpSocketLink.java:1349)
gemini-mysql: 	at com.caucho.network.listen.TcpSocketLink.handleRequestsImpl(TcpSocketLink.java:1333)
gemini-mysql: 	at com.caucho.network.listen.TcpSocketLink.handleRequests(TcpSocketLink.java:1241)
gemini-mysql: 	at com.caucho.network.listen.TcpSocketLink.handleAcceptTaskImpl(TcpSocketLink.java:1037)
gemini-mysql: 	at com.caucho.network.listen.ConnectionTask.runThread(ConnectionTask.java:117)
gemini-mysql: 	at com.caucho.network.listen.ConnectionTask.run(ConnectionTask.java:93)
gemini-mysql: 	at com.caucho.network.listen.SocketLinkThreadLauncher.handleTasks(SocketLinkThreadLauncher.java:175)
gemini-mysql: 	at com.caucho.network.listen.TcpSocketAcceptThread.run(TcpSocketAcceptThread.java:61)
gemini-mysql: 	at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
gemini-mysql: 	at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
gemini-mysql: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
gemini-mysql: 	at jdk.internal.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source)
gemini-mysql: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
gemini-mysql: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
gemini-mysql: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
gemini-mysql: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
gemini-mysql: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
gemini-mysql: 	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
gemini-mysql: 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:91)
gemini-mysql: 	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
gemini-mysql: 	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:956)
gemini-mysql: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:826)
gemini-mysql: 	... 38 more
gemini-mysql: Caused by: java.net.NoRouteToHostException: Cannot assign requested address (Address not available)
gemini-mysql: 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
gemini-mysql: 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
gemini-mysql: 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
gemini-mysql: 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
gemini-mysql: 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
gemini-mysql: 	at java.base/java.net.Socket.connect(Socket.java:591)
gemini-mysql: 	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
gemini-mysql: 	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:65)
gemini-mysql: 	... 41 more
```

Does this happen with gemini-hikaricp?  I'm guessing not, but I wasn't able to figure out how to use it within an hour so I gave up.

**Comment by bhauer** [comment]
If the configuration doesn't have as many connections as the concurrency level of the test, it will probably create ad hoc connections.  I think the concurrency level if 512, right?  The configuration should be changed to maintain at least 512 connections.

**Comment by msmith-techempower** [comment]
I am supposing that [these lines](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Java/gemini/src/main/webapp/WEB-INF/configuration/gemini-mysql.conf#L99) are to what @bhauer is referring.

Is this a bug in Gemini, or a feature and a misuse in TFB?

**Comment by bhauer** [comment]
@msmith-techempower That's correct.  If we're using the legacy connection pool (and it looks like we are from those log messages), then the configuration should provide at least 512 connections if the concurrency level is 512.
